spring.application.name=client-service
server.port=5001
eureka.instance.prefer-ip-address=true

##database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

##log4j config
logging.config=classpath:log4j2.xml
logging.level.root=ERROR
logging.level.com.org.clientService=INFO
logging.level.org.springframework.boot.autoconfigure=DEBUG

##key config
jwt.public-key=classpath:keys/gateway-public.pem

##kafka server properties
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# Serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=true

##actuator
management.endpoints.web.exposure.include=health
