spring.application.name=therapist-service
server.port=5002

##database connection properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

##kafka server properties
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.auto-offset-reset=earliest

##log4j
logging.config=classpath:log4j2.xml
logging.level.root=ERROR
logging.level.com.org.therapistService=INFO
logging.level.org.springframework.boot.autoconfigure=DEBUG

jwt.secret=${JWT_SECRET}