spring.application.name=analytics-service
server.port=5006
eureka.instance.prefer-ip-address=true

##database connection properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

##kafka server properties
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.auto-offset-reset=earliest

# Delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Error handling deserializers
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Consumer group
spring.kafka.consumer.group-id=analytics-service-events

# JSON config
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Serializers (needed for DLT publishing)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=true

##log4j
logging.config=classpath:log4j2.xml
logging.level.root=ERROR
logging.level.com.org.analyticsService=INFO
logging.level.org.springframework.boot.autoconfigure=DEBUG

##jackson config
spring.jackson.serialization.write-dates-as-timestamps=false

##key config
jwt.public-key=classpath:keys/gateway-public.pem