spring.application.name=notification-service
server.port=5003

##kafka server properties
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=notification-service-email-events
spring.kafka.consumer.auto-offset-reset=earliest

##mail properties to be setup

##log4j config
logging.config=classpath:log4j2.xml
logging.level.root=ERROR
logging.level.com.org.notificationService=INFO
logging.level.org.springframework.boot.autoconfigure=DEBUG