spring.application.name=NotificationService
server.port=5003
##kafka server properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=reminder-group-service
spring.kafka.consumer.auto-offset-reset=earliest
##mail properties to be setup