spring.application.name=NotificationService
server.port=5003
##kafka server properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=reminder-group-service
spring.kafka.consumer.auto-offset-reset=earliest
##mail properties to be setup

logging.config=classpath:log4j2.xml
logging.level.root=ERROR
logging.level.com.org.notificationService=INFO
logging.level.org.springframework.boot.autoconfigure=DEBUG