spring.application.name=gateway-service
server.port=8091

spring.cloud.gateway.server.webmvc.discovery.locator.enabled=false
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=false

spring.cloud.gateway.server.webmvc.routes[0].id=therapistId_route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://THERAPIST-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/therapist/{tid}/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=AddRequestHeader=X-Therapist-ID, {tid}
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=client_route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://CLIENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/client/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=therapist_route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://THERAPIST-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/therapist/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

logging.level.org.springframework.boot.autoconfigure=DEBUG