spring.application.name=DiscoveryService
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.config=classpath:log4j2.xml
logging.level.root=ERROR
logging.level.com.org.discoveryService=INFO
logging.level.org.springframework.boot.autoconfigure=DEBUG